services:
  - type: web
    name: buildpilot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: buildpilot_api.settings
      - key: OPENAI_API_KEY
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"